const {chromium}=require('@playwright/test');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://localhost:5174/#Overview');await p.getByRole('button',{name:'Add vehicle',exact:true}).click();await p.getByLabel('Vehicle number').fill('WORK123');await p.getByRole('button',{name:'Add to queue'}).click();await p.getByLabel('Queue order').selectOption('Balanced priority');assert.match(await p.locator('.allocation-advice').innerText(),/WORK123 → A1/);await p.getByRole('button',{name:'Park next vehicle'}).click();assert.match(await p.locator('.operations-summary').innerText(),/Arrivals\s+1/);
 await p.goto('http://localhost:5174/#Reservations');await p.getByLabel('Visitor name').fill('Visitor');await p.getByLabel('Vehicle plate').fill('TIMED123');await p.getByLabel('Hold duration').selectOption('15');await p.getByRole('button',{name:'Hold bay',exact:true}).click();assert.match(await p.locator('.expiry-time').innerText(),/Expires/);
 const backup=await p.evaluate(()=>({format:'parkwise-backup-v1',state:JSON.parse(localStorage.getItem('parkwise-workspace-v2'))}));
 await p.goto('http://localhost:5174/#Workspace');await p.getByLabel('Restore from backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.getByRole('button',{name:'Keep current records'}).click();assert.equal(await p.locator('.restore-review').count(),0);
 await p.getByLabel('Restore from backup').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});assert.match(await p.getByRole('alert').innerText(),/Parkwise/);
 await p.getByLabel('Restore from backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.getByRole('button',{name:'Replace workspace with backup'}).click();await p.reload();assert.match(await p.locator('.capacity-grid').innerText(),/A1\s+Occupied/);
 await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('parkwise-workspace-v2'));s.reservations[0].expiresAt=new Date(Date.now()-1000).toISOString();localStorage.setItem('parkwise-workspace-v2',JSON.stringify(s))});await p.goto('http://localhost:5174/#Reservations');await p.reload();assert.match(await p.locator('.reservation-list').innerText(),/Expired/);assert.equal(await p.getByRole('button',{name:'Check in TIMED123'}).count(),0);
 for(const width of [390,768,1440]){await p.setViewportSize({width,height:1000});for(const route of ['Overview','Reservations','Workspace']){await p.goto('http://localhost:5174/#'+route);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${route} overflow ${width}`)}}
 assert.deepEqual(errors,[]);await b.close();console.log('PASS explained allocation, operations summary, timed expiry, validated backup review/restore and responsive layouts');})().catch(e=>{console.error(e);process.exit(1)});
