import {useMemo,useState} from 'react';
import {Play,Database,X} from 'lucide-react';
import {sample,schedule} from '../algorithms/scheduling';
import {Panel,PageTitle,Badge,ConceptNote} from '../components/UI';
export default function Processes({state,algorithm,setAlgorithm,quantum,setQuantum,selected,setSelected}){
 const [input,setInput]=useState(sample),[result,setResult]=useState(null),[error,setError]=useState('');
 const process=state.processes.find(p=>p.pid===selected);
 const colors=['#337762','#ab7540','#64849a','#89729c'];
 const source=useMemo(()=>Object.fromEntries(input.map((p,i)=>[p.pid,colors[i%4]])),[input]);
 function run(){try{setResult(schedule(input,algorithm,quantum));setError('')}catch(e){setError(e.message)}}
 return <><PageTitle title="Processes & scheduling" description="Inspect the PCB. Then decide which request gets CPU time."/>
 <Panel title="Process control blocks" aside={<Badge>{state.processes.length+' processes'}</Badge>}><div className="table-scroll"><table><thead><tr>{['PID','Vehicle','State','Arrival','Burst','Priority','Assigned slot'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{state.processes.map(p=><tr key={p.pid}><td><button className="pid-button" onClick={()=>setSelected(p.pid)}>{p.pid}</button></td><td>{p.vehicleNumber}</td><td><Badge>{p.state}</Badge></td><td>{p.arrivalTime}</td><td>{p.burstTime}</td><td>{p.priority}</td><td>{p.assignedSlot||'—'}</td></tr>)}</tbody></table>{!state.processes.length&&<p className="empty">No processes yet. Add a vehicle or load dashboard demo data.</p>}</div></Panel>
 {process&&<Panel title={`PCB / ${process.pid}`} aside={<button aria-label="Close PCB" onClick={()=>setSelected(null)}><X size={16}/></button>}><p className="panel-copy">A PCB stores the information an operating system uses to manage a process.</p><dl className="pcb-grid">{Object.entries({PID:process.pid,Vehicle:process.vehicleNumber,State:process.state,Arrival:process.arrivalTime,Burst:process.burstTime,Priority:process.priority,Slot:process.assignedSlot||'Unassigned','Waiting time':process.waitingTime??'Not allocated','Turnaround time':process.turnaroundTime??'Not terminated'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="state-flow">{['NEW','READY','RUNNING','TERMINATED'].map(s=><Badge key={s} tone={process.state===s?'active-state':''}>{s}</Badge>)}<span>RUNNING → <Badge tone={process.state==='WAITING'?'active-state':''}>WAITING</Badge> → READY</span></div><p className="panel-copy">History: {process.history.map(h=>`${h.state} (t=${h.time})`).join(' → ')}</p></Panel>}
 <Panel title="CPU scheduling laboratory" aside={<span className="muted">Independent calculation sandbox</span>}><div className="scheduler-controls"><label>Algorithm<select aria-label="Algorithm" value={algorithm} onChange={e=>{setAlgorithm(e.target.value);setResult(null)}}><option>FCFS</option><option>Priority</option><option>Round Robin</option></select></label><label>Time quantum<input aria-label="Time quantum" type="number" min="1" max="100" disabled={algorithm!=='Round Robin'} value={quantum} onChange={e=>{setQuantum(Number(e.target.value));setResult(null)}}/></label><button onClick={()=>{setInput(sample.map(p=>({...p})));setResult(null);setError('')}}><Database size={15}/>Sample data</button><button onClick={()=>{setInput(state.processes.filter(p=>p.state==='READY').map(({pid,arrivalTime,burstTime,priority})=>({pid,arrivalTime,burstTime,priority})));setResult(null)}}>Use ready queue</button><button className="primary" onClick={run}><Play size={15}/>Run scheduler</button></div><p className="panel-copy">{algorithm==='FCFS'?'First come, first served. Requests run in arrival order.':algorithm==='Priority'?'Non-preemptive priority. Lower numbers are more urgent; only arrived requests can be selected.':'Round Robin shares CPU time in bounded slices. Arrivals at a slice boundary enter before the preempted process.'} Burst time models CPU service, not parking duration.</p><div className="table-scroll"><table className="editable-table"><thead><tr><th>Process</th><th>Arrival time</th><th>Burst time</th><th>Priority (1–4)</th></tr></thead><tbody>{input.map((p,i)=><tr key={p.pid}><td><b>{p.pid}</b></td>{['arrivalTime','burstTime','priority'].map(k=><td key={k}><input aria-label={`${p.pid} ${k}`} type="number" min={k==='arrivalTime'?0:1} max={k==='priority'?4:k==='burstTime'?100:10000} value={p[k]} onChange={e=>{setInput(input.map((x,j)=>j===i?{...x,[k]:Number(e.target.value)}:x));setResult(null)}}/></td>)}</tr>)}</tbody></table></div>{error&&<p className="error" role="alert">{error}</p>}
 {result&&<div className="schedule-results"><div className="result-heading"><h3>Execution timeline</h3><div><span>Avg. waiting <b>{result.averageWaitingTime.toFixed(2)}</b></span><span>Avg. turnaround <b>{result.averageTurnaroundTime.toFixed(2)}</b></span></div></div><div className="gantt" aria-label="Gantt chart">{result.segments.map((s,i)=><div key={i} style={{flexGrow:s.end-s.start,background:source[s.pid]||'#65726c'}}><b>{s.pid}</b><span>{s.start}–{s.end}</span></div>)}</div>{!result.segments.length&&<p>No ready processes to schedule.</p>}<div className="table-scroll"><table><thead><tr>{['PID','Completion','Turnaround','Waiting'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{result.stats.map(p=><tr key={p.pid}><td>{p.pid}</td><td>{p.completionTime}</td><td>{p.turnaroundTime}</td><td>{p.waitingTime}</td></tr>)}</tbody></table></div></div>}</Panel><ConceptNote>Vehicle arrives → process created → ready queue → scheduler → parking allocation → parking slot. Turnaround = completion − arrival; waiting = turnaround − CPU burst in this calculation sandbox.</ConceptNote></>;
}
