import {useState} from 'react';
import {Panel,PageTitle} from '../components/UI';
import {availableSlots,holdBay,cancelHold,checkInHold,displayTime,activeHold} from '../domain/parking';
export default function Reservations({state,setState}){
 const [name,setName]=useState(''),[plate,setPlate]=useState(''),[category,setCategory]=useState(4),[slot,setSlot]=useState(''),[holdMinutes,setHoldMinutes]=useState(30),[message,setMessage]=useState(''),[error,setError]=useState('');
 const eligible=availableSlots(state).filter(s=>s!=='C4'||category===3),activeSlot=eligible.includes(slot)?slot:eligible[0]||'';
 function act(fn,success){try{setState(fn(state));setError('');setMessage(success);return true}catch(e){setError(e.message);return false}}
 return <><PageTitle title="Visitor reservations" description="Hold an available bay now, then check your visitor in on arrival."/><p className="feature-note">A hold removes the bay from general allocation immediately. Timed holds release automatically when the visitor does not arrive. Existing untimed holds remain active until cancelled.</p>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="action-notice" role="status">{message}</p>}<Panel title="Create a bay hold"><form className="reservation-form" onSubmit={e=>{e.preventDefault();if(act(s=>holdBay(s,{name,vehicleNumber:plate,slot:activeSlot,priority:category,holdMinutes}),'Visitor bay held.')){setName('');setPlate('')}}}><label>Visitor name<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/></label><label>Vehicle plate<input required maxLength={15} value={plate} onChange={e=>setPlate(e.target.value)} placeholder="MH12 AB1234"/></label><label>Category<select value={category} onChange={e=>setCategory(Number(e.target.value))}><option value={4}>Standard</option><option value={2}>Accessible</option><option value={3}>Reserved</option><option value={1}>Emergency</option></select></label><label>Hold bay<select aria-label="Hold bay" required value={activeSlot} onChange={e=>setSlot(e.target.value)}>{!eligible.length&&<option value="">No eligible bays</option>}{eligible.map(s=><option key={s}>{s}</option>)}</select></label><label>Hold duration<select value={holdMinutes} onChange={e=>setHoldMinutes(Number(e.target.value))}>{[15,30,60,120].map(m=><option value={m} key={m}>{m} minutes</option>)}</select></label><button className="primary" disabled={!activeSlot}>Hold bay</button></form></Panel><Panel title="Reservation register" aside={<span className="system-status">{(state.reservations||[]).filter(r=>activeHold(r)).length} active holds</span>}><div className="reservation-list">{!(state.reservations||[]).length?<p className="register-empty">Your visitor holds will appear here.</p>:(state.reservations||[]).map(r=><article className="reservation-row" key={r.id}><div><strong>{r.name}</strong><p>{r.vehicleNumber} · {r.id}</p><small>Created {displayTime(r.createdAt)}</small>{r.expiresAt&&<small className="expiry-time">Expires {displayTime(r.expiresAt)}</small>}</div><div className="reservation-bay">{r.slot}<small>{r.status==='checked-in'?'Checked in':r.status==='cancelled'?'Cancelled':activeHold(r)?'Held':'Expired'}</small></div>{activeHold(r)&&<div className="actions"><button className="primary" aria-label={`Check in ${r.vehicleNumber}`} onClick={()=>act(s=>checkInHold(s,r.id),`${r.vehicleNumber} checked in to ${r.slot}.`)}>Check in</button><button aria-label={`Cancel reservation ${r.vehicleNumber}`} onClick={()=>act(s=>cancelHold(s,r.id),'Hold cancelled; bay released.')}>Cancel hold</button></div>}</article>)}</div></Panel></>;
}
