import {useState} from 'react';
import {Panel,PageTitle} from '../components/UI';
import {slots,bayStatus,toggleBayBlock,restoreBackup} from '../domain/parking';
export default function Workspace({state,setState,onRestore,isSample}){
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState(null);
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({format:'parkwise-backup-v1',exportedAt:new Date().toISOString(),workspace:isSample?'sample':'local',state},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`parkwise-${isSample?'sample':'workspace'}-backup.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Backup downloaded. Keep it with your project files.');}
 async function readBackup(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>5000000)throw Error('Backup must be smaller than 5 MB.');const restored=restoreBackup(JSON.parse(await file.text()));setPending(restored);setError('');setMessage('Backup validated. Review the record counts before replacing this workspace.')}catch(e){setPending(null);setError(e instanceof SyntaxError?'This file is not valid JSON.':e.message)}}
 return <><PageTitle title="Workspace" description="Control usable capacity and maintain your parking records."/>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="action-notice">{message}</p>}<div className="workspace-panels"><Panel title="Workspace records"><div className="workspace-copy"><p>{isSample?'You are using sample records, stored separately from your real workspace.':'Your daily workspace starts with your actual arrivals. Example records are available in a separate workspace.'}</p><a className="action-link" href={isSample?'/?workspace=local#Overview':'/?workspace=sample#Overview'}>{isSample?'Return to real workspace':'Open example records'} →</a><p className="feature-note">The sample includes parked vehicles, an arrival queue, a visitor hold and a maintenance block.</p></div></Panel><Panel title="Backup and recovery"><div className="workspace-copy"><p>Save all vehicle records, holds, bay blocks and activity as a JSON file.</p><button onClick={download}>Download workspace backup</button><label className="backup-upload">Restore from backup<input type="file" accept=".json,application/json" onChange={readBackup}/></label>{pending&&<div className="restore-review"><p>{pending.processes.length} visits · {pending.reservations.length} reservations · {pending.blockedSlots.length} blocked bays. This replaces the current {isSample?'sample':'local'} workspace.</p><div className="actions"><button className="primary" onClick={()=>{(onRestore||setState)(pending);setPending(null);setMessage('Workspace restored successfully.')}}>Replace workspace with backup</button><button onClick={()=>{setPending(null);setMessage('Restore cancelled.')}}>Keep current records</button></div></div>}<p className="feature-note">Stored on this browser only. CSV reports are available on the Vehicles page.</p></div></Panel></div><Panel title="Bay availability"><p className="workspace-copy">Block empty bays for maintenance. Occupied or held bays must be released first.</p><div className="capacity-grid">{slots.map(slot=>{const {kind}=bayStatus(state,slot),disabled=kind==='occupied'||kind==='held';return <div key={slot}><strong>{slot}</strong><span>{kind==='blocked'?'Out of service':kind==='occupied'?'Occupied':kind==='held'?'Visitor hold':slot==='C4'?'Reserved category':'Available'}</span><button aria-label={`${kind==='blocked'?'Reopen':'Block'} ${slot}`} disabled={disabled} onClick={()=>{try{setState(toggleBayBlock(state,slot));setError('');setMessage(`${slot} ${kind==='blocked'?'reopened':'blocked for maintenance'}.`)}catch(e){setError(e.message)}}}>{kind==='blocked'?'Reopen bay':'Block bay'}</button></div>})}</div></Panel></>;
}
