import {displayTime,availableSlots} from '../domain/parking';
import {useState} from 'react';
import {Download,Search,LogOut} from 'lucide-react';
import {Panel} from './UI';
const status=p=>p.assignedSlot?'Parked':p.cancelled?'Cancelled':p.state==='TERMINATED'?'Exited':'Queued';
const priorities={1:'Emergency',2:'Accessible',3:'Reserved',4:'Standard'};
export function vehicleCsv(processes){
 const cell=value=>'"'+String(value??'').replace(/"/g,'""').replace(/^[=+@\-]/,"'$&")+'"';
 return [['Visit','Vehicle','Status','Bay','Category','Arrived','Parked','Exited'],...processes.map(p=>[p.pid,p.vehicleNumber,status(p),p.assignedSlot||p.lastSlot||'',priorities[p.priority],p.arrivedAt||'',p.parkedAt||'',p.exitedAt||''])].map(row=>row.map(cell).join(',')).join('\r\n');
}
export default function ParkingOperations({state,onExit,onCancel,view}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[page,setPage]=useState(0);
 const occupied=state.processes.filter(p=>p.assignedSlot);
 const records=state.processes.filter(p=>(filter==='All'||status(p)===filter)&&[p.vehicleNumber,p.pid,p.assignedSlot||p.lastSlot||''].some(v=>v.toLowerCase().includes(query.trim().toLowerCase()))).slice().reverse();
 const lastPage=Math.max(0,Math.ceil(records.length/8)-1),current=Math.min(page,lastPage);
 function download(){const url=URL.createObjectURL(new Blob(['\ufeff'+vehicleCsv(records)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='parkwise-vehicles.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <>{view!=="register"&&<Panel title="Space utilization" aside={<span className="system-status">{Math.round(occupied.length/12*100)}% occupied</span>}><div className="utilization-grid">{['A','B','C'].map(zone=>{const count=occupied.filter(p=>p.assignedSlot.startsWith(zone)).length;return <div key={zone}><div><strong>Zone {zone}</strong><span>{count} / 4 occupied</span></div><div className="zone-meter" role="meter" aria-label={`Zone ${zone} occupancy`} aria-valuemin={0} aria-valuemax={4} aria-valuenow={count}><span style={{width:`${count*25}%`}}/></div><small>{availableSlots(state).filter(s=>s.startsWith(zone)).length} available {zone==='C'?'· includes reserved bay C4':''}</small></div>})}</div></Panel>}
 {view!=="utilization"&&<Panel title="Vehicle register" aside={<button onClick={download} disabled={!records.length}><Download size={16}/>Export CSV</button>}><div className="register-toolbar"><label className="vehicle-search"><Search size={17}/><input type="search" aria-label="Search vehicle register" placeholder="Search plate, visit or bay" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><label>Status<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}>{['All','Parked','Queued','Exited','Cancelled'].map(x=><option key={x}>{x}</option>)}</select></label><span role="status">{records.length} matching {records.length===1?'vehicle':'vehicles'}</span></div><div className="table-scroll"><table className="vehicle-register"><thead><tr>{['Vehicle / visit','Status','Bay','Category','Arrival / departure','Action'].map(x=><th scope="col" key={x}>{x}</th>)}</tr></thead><tbody>{records.slice(current*8,current*8+8).map(p=><tr key={p.pid}><td><strong>{p.vehicleNumber}</strong><small>{p.pid}</small></td><td><span className={'register-state '+status(p).toLowerCase()}>{status(p)}</span></td><td>{p.assignedSlot||p.lastSlot||'—'}</td><td>{priorities[p.priority]}</td><td><small>In: {displayTime(p.arrivedAt)}</small><small>Out: {p.exitedAt?displayTime(p.exitedAt):p.state==='TERMINATED'?'Not recorded':'—'}</small></td><td>{p.assignedSlot?<button aria-label={`Check out ${p.vehicleNumber}`} onClick={()=>onExit(p.pid)}><LogOut size={15}/>Check out</button>:status(p)==='Queued'&&onCancel?<button aria-label={`Cancel arrival ${p.vehicleNumber}`} onClick={()=>onCancel(p.pid)}>Cancel arrival</button>:<span className="muted">—</span>}</td></tr>)}</tbody></table></div>{!records.length&&<p className="register-empty">{state.processes.length?'No vehicles match these filters.':'Your vehicle register will appear here after the first arrival.'}</p>}<div className="register-pagination"><span>Page {current+1} of {lastPage+1} · All saved visits</span><div><button disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><button disabled={current===lastPage} onClick={()=>setPage(current+1)}>Next</button></div></div></Panel>}</>;
}
