import React,{useEffect,useRef,useState,lazy,Suspense} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,ArrowRight,CarFront,Command,ShieldCheck,Workflow,Layers,ListOrdered,BookOpen,Check,ChevronRight,Play,LockKeyhole} from 'lucide-react';
import gsap from 'gsap';
import {SplitText} from 'gsap/SplitText';
import {Flip} from 'gsap/Flip';
import {DrawSVGPlugin} from 'gsap/DrawSVGPlugin';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
gsap.registerPlugin(SplitText,Flip,DrawSVGPlugin,ScrollTrigger);
const GridBackground=lazy(()=>import('./grid-shader'));
type Process={pid:string;vehicleNumber:string;state:string;priority:number;assignedSlot:string|null};
type Props={navigate:(page:string)=>void;scrollTo:(target:string)=>void;state:{processes:Process[]};algorithm:string;setAlgorithm:(value:string)=>void};
const modules=[
 {name:'Processes & scheduling',title:'The right request. At the right time.',description:'See FCFS, Priority, and Round Robin turn a queue of arrivals into a calculated execution timeline.',icon:Layers,tag:'SCHEDULING',detail:'3 algorithms'},
 {name:'Synchronization',title:'One bay. Zero conflicts.',description:'Run the race condition, then add a lock. Watch mutual exclusion protect a shared parking resource.',icon:ShieldCheck,tag:'CONCURRENCY',detail:'Step-by-step playback'},
 {name:'Producer–consumer',title:'Keep the requests moving.',description:'Produce, queue, consume. Explore the full and empty conditions of a bounded buffer.',icon:ListOrdered,tag:'BOUNDED BUFFER',detail:'5 request capacity'},
 {name:'Deadlock',title:'Break the waiting game.',description:'Follow a circular resource dependency, identify the conflict, and recover the system.',icon:Workflow,tag:'RESOURCE MANAGEMENT',detail:'Visual recovery'},
];
const bays=Array.from({length:12},(_,i)=>`${'ABC'[Math.floor(i/4)]}${i%4+1}`);
export const Button=React.forwardRef<HTMLButtonElement,React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'default'|'secondary'|'ghost'}>(({variant='default',className='',children,...props},ref)=><button ref={ref} className={`premium-button ${variant} ${className}`} {...props}>{children}</button>);
Button.displayName='Button';
export default function SaaSTemplate({navigate,scrollTo,state,algorithm,setAlgorithm}:Props){
 const root=useRef<HTMLDivElement>(null),title=useRef<HTMLHeadingElement>(null),queueRef=useRef<HTMLDivElement>(null),flipTween=useRef<gsap.core.Timeline|null>(null);
 const [tab,setTab]=useState(0);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const occupied=state.processes.filter(p=>p.assignedSlot);const ready=state.processes.filter(p=>['READY','WAITING'].includes(p.state));const queue=algorithm==='Priority'?[...ready].sort((a,b)=>a.priority-b.priority):ready;
 useEffect(()=>{const ctx=gsap.context(()=>{if(reduced)return;
  SplitText.create(title.current!,{type:'lines',mask:'lines',autoSplit:true,onSplit(self){return gsap.from(self.lines,{yPercent:105,duration:1.1,stagger:.12,ease:'power4.out'})}});
  gsap.from('.hero-intro,.hero-actions,.hero-assurance',{y:20,opacity:0,duration:.9,stagger:.12,delay:.2,ease:'power3.out'});
  gsap.from('.product-window',{y:60,opacity:0,duration:1.15,delay:.35,ease:'power3.out'});
  gsap.to('.preview-aura',{scale:1.08,opacity:.7,duration:4,repeat:-1,yoyo:true,ease:'sine.inOut'});
  gsap.utils.toArray<HTMLElement>('[data-reveal]').forEach(el=>gsap.from(el,{y:32,opacity:0,duration:.9,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 92%',once:true}}));
  gsap.from('.flow-stroke',{drawSVG:'0%',duration:1.5,ease:'power2.inOut',scrollTrigger:{trigger:'.system-flow',start:'top 80%',once:true}});
 },root);return()=>{flipTween.current?.kill();ctx.revert()}},[reduced]);
 function changePolicy(value:string){const snapshot=queueRef.current?Flip.getState(queueRef.current.children):null;flushSync(()=>setAlgorithm(value));if(snapshot&&!reduced){flipTween.current?.kill();flipTween.current=Flip.from(snapshot,{duration:.6,ease:'power3.inOut',absolute:false})}}
 const active=modules[tab];
 return <div className="premium-home" ref={root}>
 <div className="homepage-grid" aria-hidden="true"><Suspense fallback={null}><GridBackground decorative/></Suspense></div>
 <section className="premium-hero"><div className="release-pill hero-intro"><span className="pulse-dot"/>A smarter way to understand operating systems<ChevronRight size={13}/></div><h1 ref={title}>A place for every car.<br/><span className="hero-second">A process behind every space.</span></h1><p className="hero-intro hero-description">Bring operating systems out of the textbook.<br/>An interactive parking lab for scheduling, shared resources,<br className="desktop-only"/> and the moments when everything needs to work together.</p><div className="hero-actions"><Button onClick={()=>navigate('Dashboard')}>Launch the parking lab <ArrowRight size={16}/></Button><Button variant="ghost" onClick={()=>scrollTo('#modules')}><Play size={13}/>Explore the concepts</Button></div><div className="hero-assurance"><span><Check size={13}/>Runs in your browser</span><span><Check size={13}/>Built for hands-on learning</span></div>
 <div className="product-showcase"><div className="preview-aura" aria-hidden="true"/><div className="product-window"><div className="window-top"><div className="window-dots"><i/><i/><i/></div><span><LockKeyhole size={10}/>parkwise / control center</span><button onClick={()=>navigate('Dashboard')} aria-label="Open full dashboard"><ArrowUpRight size={16}/></button></div><div className="preview-shell"><aside className="preview-sidebar" aria-hidden="true"><Command size={21}/><div className="mini-active"><CarFront size={17}/></div><Layers size={17}/><ShieldCheck size={17}/><Workflow size={17}/></aside><div className="preview-content"><div className="preview-heading"><div><h2>Your parking, at a glance.</h2><p>Ground level · All systems in view</p></div><span className="preview-live"><i/>Live state</span></div><div className="preview-metrics">{[['Parking bays',12],['Occupied',occupied.length],['In the queue',ready.length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}<small>{label==='Parking bays'?'total':label==='Occupied'?'allocated':'requests'}</small></strong></div>)}</div><div className="preview-workspace"><div className="preview-map"><div className="preview-section-title"><span>Parking map</span><small><i/>Available <i/>Occupied</small></div><div className="preview-bays">{bays.map(id=>{const p=occupied.find(p=>p.assignedSlot===id);return <button key={id} className={p?'filled':id==='C4'?'reserved':''} onClick={()=>navigate('Dashboard')} aria-label={`Open parking map: ${id}`}><span>{id}</span>{p?<CarFront size={29} strokeWidth={1.3}/>:<b>{id==='C4'?'R':'P'}</b>}<small>{p?p.pid:id==='C4'?'Reserved':'Available'}</small></button>})}</div><div className="preview-lane"><ArrowRight size={14}/><span/><ArrowRight size={14}/></div></div><div className="preview-queue"><div className="preview-section-title"><span>Ready queue</span><small>{ready.length} requests</small></div><div className="policy-selector" aria-label="Preview allocation policy">{['FCFS','Priority'].map(value=><button aria-pressed={algorithm===value} key={value} onClick={()=>changePolicy(value)}>{value}</button>)}</div><div ref={queueRef} className="preview-requests">{queue.slice(0,3).map(p=><div key={p.pid} data-flip-id={p.pid}><div className="request-icon"><CarFront size={17}/></div><div><b>{p.vehicleNumber}</b><small>{p.pid} · Priority {p.priority}</small></div><span className={p.priority===1?'urgent':''}/></div>)}{!queue.length&&<p>No requests waiting.<br/>Add a vehicle in the dashboard.</p>}</div><button className="preview-open" onClick={()=>navigate('Dashboard')}>Manage parking <ArrowUpRight size={14}/></button><p className="preview-caption">Change the policy.<br/>Watch the queue respond.</p></div></div></div></div><div className="window-status"><span><i/>Local simulation</span><span>12 resources. One coordinated system.</span></div></div></div></section>
 <section className="principle-strip" aria-label="Operating system concepts"><span>REAL CONCEPTS.<br/>VISIBLE CONNECTIONS.</span>{[['Process',Layers],['Scheduling',ListOrdered],['Mutual exclusion',ShieldCheck],['Deadlock',Workflow]].map(([label,Icon])=>{const Symbol=Icon as typeof Layers;return <div key={String(label)}><Symbol size={20}/>{String(label)}</div>})}</section>
 <section className="modules-section" id="modules"><div className="section-intro" data-reveal><span className="section-label">THE LAB, UNPACKED</span><h2>Big concepts.<br/><span>Beautifully clear.</span></h2><p>Less imagining what an operating system does.<br/>More seeing it happen, one interaction at a time.</p></div><div className="module-grid">{modules.map((m,i)=><button data-reveal className="module-card" key={m.name} onClick={()=>navigate(m.name)}><div className="module-card-top"><m.icon size={23} strokeWidth={1.4}/><span>0{i+1}</span></div><div className={`module-graphic graphic-${i}`} aria-hidden="true">{i===0?<><i>P1</i><i>P2</i><i>P3</i><i>P1</i></>:i===1?<><span>P101</span><LockKeyhole size={28}/><span>A1</span></>:i===2?<>{[0,1,2,3,4].map(n=><i key={n} className={n<3?'full':''}>{n<3?<CarFront size={18}/>:null}</i>)}</>:<><span>P1</span><Workflow size={44}/><span>P2</span></>}</div><span className="module-tag">{m.tag}</span><h3>{m.title}</h3><p>{m.description}</p><div className="module-card-bottom"><span>{m.detail}</span><ArrowUpRight size={18}/></div></button>)}</div></section>
 <section className="system-flow" id="how-it-works"><div className="section-intro" data-reveal><span className="section-label">CONNECTED BY DESIGN</span><h2>From arrival to allocation.<br/><span>Follow every decision.</span></h2></div><div className="flow-diagram" data-reveal><svg viewBox="0 0 1000 50" preserveAspectRatio="none" aria-hidden="true"><path className="flow-stroke" d="M100 25H900"/></svg>{[['Vehicle arrives',CarFront,'A request enters the system.'],['Process created',Layers,'A PCB gives it an identity.'],['Scheduler selects',ListOrdered,'A policy decides who goes next.'],['Bay allocated',Check,'A shared resource finds its owner.']].map(([name,Icon,copy])=>{const Symbol=Icon as typeof Layers;return <div key={String(name)}><span><Symbol size={23}/></span><h3>{String(name)}</h3><p>{String(copy)}</p></div>})}</div><div className="concept-explorer" data-reveal><div className="explorer-tabs" role="tablist" aria-label="Explore a concept">{modules.map((m,i)=><button key={m.name} id={`concept-tab-${i}`} role="tab" aria-selected={tab===i} aria-controls="concept-panel" tabIndex={tab===i?0:-1} onClick={()=>setTab(i)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;setTab(next);document.getElementById(`concept-tab-${next}`)?.focus()}}}>{m.name}</button>)}</div><div className="explorer-content" id="concept-panel" role="tabpanel" aria-labelledby={`concept-tab-${tab}`} key={tab}><active.icon size={36} strokeWidth={1.2}/><div><h3>{active.title}</h3><p>{active.description}</p></div><Button variant="secondary" onClick={()=>navigate(active.name)}>Try this demo <ArrowUpRight size={16}/></Button></div></div></section>
 <section className="closing-section" data-reveal><div className="closing-mark"><Command size={28}/></div><h2>Make room for<br/><span>a little understanding.</span></h2><p>Your next OS demonstration starts here.</p><Button onClick={()=>navigate('Dashboard')}>Open the parking lab <ArrowRight size={16}/></Button><button className="concepts-link" onClick={()=>navigate('OS Concepts')}>Read the concept guide <BookOpen size={14}/></button></section>
 <footer className="premium-footer"><a href="#Home" onClick={e=>{e.preventDefault();scrollTo('.premium-hero')}}>parkwise<span> / OS LAB</span></a><p>Made for learning. Designed to be explored.</p><button className="original-template-link" onClick={()=>navigate('Template')}>View original template <ArrowUpRight size={12}/></button><button className="original-template-link" onClick={()=>navigate('GridShader')}>Grid shader demo <ArrowUpRight size={12}/></button></footer>
 </div>
}
